#ifndef _DIO_CONFIG_H_
#define _DIO_CONFIG_H_

/****** PINS DIRECTION ******/

#define DIO_PIN0_DIR    OUTPUT
#define DIO_PIN1_DIR    OUTPUT
#define DIO_PIN2_DIR    OUTPUT
#define DIO_PIN3_DIR    OUTPUT
#define DIO_PIN4_DIR    OUTPUT
#define DIO_PIN5_DIR    OUTPUT
#define DIO_PIN6_DIR    OUTPUT
#define DIO_PIN7_DIR    OUTPUT
#define DIO_PIN8_DIR    OUTPUT
#define DIO_PIN9_DIR    OUTPUT
#define DIO_PIN10_DIR   OUTPUT
#define DIO_PIN11_DIR   OUTPUT
#define DIO_PIN12_DIR   OUTPUT
#define DIO_PIN13_DIR   OUTPUT
#define DIO_PIN14_DIR   OUTPUT
#define DIO_PIN15_DIR   OUTPUT
#define DIO_PIN16_DIR   OUTPUT
#define DIO_PIN17_DIR   OUTPUT
#define DIO_PIN18_DIR   OUTPUT
#define DIO_PIN19_DIR   OUTPUT
#define DIO_PIN20_DIR   OUTPUT
#define DIO_PIN21_DIR   OUTPUT
#define DIO_PIN22_DIR   OUTPUT
#define DIO_PIN23_DIR   OUTPUT
#define DIO_PIN24_DIR   OUTPUT
#define DIO_PIN25_DIR   OUTPUT
#define DIO_PIN26_DIR   OUTPUT
#define DIO_PIN27_DIR   OUTPUT
#define DIO_PIN28_DIR   OUTPUT
#define DIO_PIN29_DIR   OUTPUT
#define DIO_PIN30_DIR   OUTPUT
#define DIO_PIN31_DIR   OUTPUT

/****** PINS INITIAL VALUES ******/

#define DIO_PIN0_INIT   LOW
#define DIO_PIN1_INIT   LOW
#define DIO_PIN2_INIT   LOW
#define DIO_PIN3_INIT   LOW
#define DIO_PIN4_INIT   LOW
#define DIO_PIN5_INIT   LOW
#define DIO_PIN6_INIT   LOW
#define DIO_PIN7_INIT   LOW
#define DIO_PIN8_INIT   LOW
#define DIO_PIN9_INIT   LOW
#define DIO_PIN10_INIT  LOW
#define DIO_PIN11_INIT  LOW
#define DIO_PIN12_INIT  LOW
#define DIO_PIN13_INIT  LOW
#define DIO_PIN14_INIT  LOW
#define DIO_PIN15_INIT  LOW
#define DIO_PIN16_INIT  LOW
#define DIO_PIN17_INIT  LOW
#define DIO_PIN18_INIT  LOW
#define DIO_PIN19_INIT  LOW
#define DIO_PIN20_INIT  LOW
#define DIO_PIN21_INIT  LOW
#define DIO_PIN22_INIT  LOW
#define DIO_PIN23_INIT  LOW
#define DIO_PIN24_INIT  LOW
#define DIO_PIN25_INIT  LOW
#define DIO_PIN26_INIT  LOW
#define DIO_PIN27_INIT  LOW
#define DIO_PIN28_INIT  LOW
#define DIO_PIN29_INIT  LOW
#define DIO_PIN30_INIT  LOW
#define DIO_PIN31_INIT  LOW


#endif